### ISSUE TITLE
Implement compare view

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2374]
The compare view should be based on the PoC. This means:

- Selection of versions to compare
- A dedicated view
- Dynamic paging
- Colorized and highlighted diff
- Overview of added, removed and modified resources

cfr github style used in demo.

## Todo

- [x] Define query for desired state diff with domain types
- [x] Create storybook for page
- [x] Show resource overview
- [x] Add "Jump to resource" functionality
- [x] Fix overscroll
- [x] Show diff view
- [x] Create page layout
- [x] Write test for DesiredStateDiff page 
- [x] Write test for JumpTo button (verify list)
- [x] Remove poc example libraries
- [x] Show toggle when resource is deleted

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2374?planning-poker) with ZenHub @bartv @andraskvr @Stijnkool

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2374?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
