### ISSUE TITLE
Add facts overview to resource manager

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2379]
Add a page with a facts overview to the resource manager.

This page should contain a table similar to the resource specific tab but with an added resource id. The resource id should link to the resource details.

This page should support filtering and sorting like defined in the API ticket.

## Todo

- [x] Add blank Facts page
- [x] Add Facts link navigation to Resource
- [x] Rename current GetFacts query to GetResourceFacts
- [x] Create facts query with filter, sorting and paging types
- [x] Create Store slice for facts (store facts data unique per environment)
- [x] Create StateHelper for facts query
- [x] Create ContinuousQueryManager for facts query
- [x] Show json data blob on page
- [x] Add Toolbar with paging
- [x] Add filters to toolbar (fact `name` & `resource_id`)
- [x] Add table with sorting on headers
- [x] Add test verifying basic table usage

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2379?planning-poker) with ZenHub @bartv @andraskvr @Stijnkool
