### ISSUE TITLE
Indicate resources that have no dryrun possible

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2555]
Resource that have no agent or that have unknown (or skipped for unknown) will never get a dryrun diff.

Show these resource with the correct reason of the change. Similar to the no change we currently show.

Use an ! for those resources.

Messages for specific statuses

| Messages  | specific statuses |
| ------------- | ------------- |
| agent_down | Could not determine difference because agent {agent_name} is down |
| undefined | Could not determine difference because this resource has undefined values |
| skipped for undefined | Could not determine difference because this resource requires a resource that has undefined values |

## Todo
- [x] Investigate response data
- [x] Create mock data
- [x] Check storybook component
- [x] Implement DIffBlock changes

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2555?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
