### ISSUE TITLE
Create compare with current state page

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2558]
This page should be quite similar to the compare versions page. 
The biggest differences are:

1. For each version there are multiple compares possible because this is snapshot. 
2. On this page it is possible to request a new dryrun
2. It should show the date the dryrun was request and the progress. It is possible that a dryrun never fully completes. (Use a progress bar)
3. It should show the diff for the request dryrun, similar to the other diff view.

http://mgmt.ii.inmanta.com:8888/dashboard/#!/environment/f81be80b-8582-499f-b002-7cdd2f2df98a/dryrun/1572537092

## Todo
- [x] Create empty compliance check page (needs url param `version`, child of DesiredState page)
- [x] Create storybook entry for compliance check page
- [x] Add base page section (non sticky) for dryrun actions
- [x] Add base page section (sticky) for diff resource list with diff title
- [x] Build complex update flow (after new dryrun trigger) with dummy components and functions
- [x] Create continuous Query for dryrun list
- [x] Add store slice for dryrun list (store by envId & version)
- [x] Create onetime Query for dryrun report
- [x] Add store slice for dryrun report (story by dryrunid)
- [x] Create command to trigger new dryrun
- [x] Add dryrun button
- [x] Add support for unmodified resources to DiffWizard
- [x] Fix JumpTo action crashing when data is empty
- [x] Select most recent dryrun after triggering a new dryrun
- [x] Refactor DiffView to be reusable between Compliance Check Page and Desired State Compare Page
- [x] Add test for selected report after trigger
- [x] Add general test for ComplianceCheck page
- [x] Create loading indicator for `todo/total` progress in dropdown
- [x] Add `todo/total` to diff loading indicator

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2558?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
