### ISSUE TITLE
Resources list in the service inventory shows errors on transition

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2861]
When the resources (maybe other data as well) is open en the service transitions it is possible that the refresh shows an error. This is probably caused by first fetching the details before updating the instance state. This results in the wrong version being sent to the server.

I have only seen it here but probably other views suffer from it as well.

## Technical
It is quite complex to make the resources call be dependent on the latest executed instance call as they are both registered within the same scheduler and executed at the same time. Registered tasks within the scheduler do not have any relation to each other. They are just executed in the order the are registered.

## Solution
We cannot prevent the resources request containing on outdated version. Therefor we cannot prevent the request from
returning a 409 Conflict error response. So when we get this specific error, we know we sent the request with an outdated version. So we need to refetch the latest instance, use that version to refetch the resources.

The InstanceResources QueryManager has to be changed to handle this behaviour. When everything is successful, we just need the current default behaviour of the `QueryManager.ContinuousWithEnv` class. But when the resources request fails with a 409, we need to trigger the new behaviour.

New behaviour:
- unregister query from scheduler
- fetch latest instance
- fetch resources based on response
- if successful, show data and register query with scheduler
- if unsuccessful, redo the loop until we are successful.
We can limit the amount of retries we do to 20 for example.
When we reach the limit, we switch to the default behaviour.
Default behaviour:
Where there is an error, just show it.
Query is registered with scheduler so it updated every 5s.

The ApiHelper currently only returns an error string. When the request was not successful, we need to return more information so a QueryManager can use that data for more complex logic.

Nothing has to change on the component level.

## Todo
- [x] Adapt the ApiHelper to also return the HTTP StatusCode upon error
- [x] Create a custom InstanceResources QueryManager
- [x] QueryManager: Add loop with limit
- [x] QueryManager: Add test for loop limit
- [x] QueryManager: register with scheduler on success
- [ ] Redux Store: Update the instance in the inventory list on success (keep data in sync)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2861?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
