### ISSUE TITLE
Show the service identity on the diagnose page

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2869]
Currently the diagnose page (Service inventory) only shows the uuid. Additionally, the instance it is about is only shown when the api call returns instead of immediately. 

Also use the service identity in the diagnose error message.

![Inmanta Web Console.gif](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/d9ac36f3-e31d-49a6-ab74-5be0625db90e)

## Todo
- [ ] Remove Service Provider. It is not needed.
- [ ] Extract description out of RemoteDataView
- [ ] Use ServiceInstanceDescription
- [ ] Show id in error message

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2869?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
