### ISSUE TITLE
Show a loading state when opening the dependencies on the resources table

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#2880]
When the number of resources is opened it will show a white block and only after the data is fetched show the actual data.

Most other pages use a loading state.![Inmanta Web Console (2).gif](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/7651c9b0-42f4-47c2-a7df-f885e34c4b03)

# Todo
- [x] There already is a loading mechanism. Lower the delay from 500ms to 200ms.
- [x] The loading view should be equally high as the resulting table. (We know the number of dependencies so we know the number of rows)
- [x] Try to add the Skeleton loading component to the requires table. This can replace the default Loading spinner. Which is too big anyway when there are only 1 or 2 rows.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/2880?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
