### ISSUE TITLE
Add first and last buttons to pagination for service instances

### ISSUE THREAD

**Issue by Stijnkool** [inmanta/web-console#298]
# TODO
- [ ] Use self link for retry mechanism
- [ ] Use self link for auto updating mechanism
- [ ] Add "first" button `<<` with first link
- [ ] Add "last" button `>>` with last link
