### ISSUE TITLE
Add status filter to the compare view

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3007]
For large models the current compare view can contain many resources that actually are not of interest.

The goal of this ticket is to add a filter so that the jump to + the list of changes actually only show the resources with the selected diff status.

I think we can put this next to the dryrun selection box (same position for compare)

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/0986e9d0-fb35-4593-9246-4c5283fb3285)

# Todo
- [x] Create StatusFilter component
- [x] Create stories for StatusFilter
- [x] Add filter to compliance check page
- [x] Write test for compliance check page
- [x] Add filter to desired state compare page
- [x] Write test for compare page

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3007?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
