### ISSUE TITLE
Add notification badge to the header

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3055]
Add a notification badge to the header as the icon most to the left in the list

https://www.patternfly.org/v4/components/notification-badge/design-guidelines

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/903ce85f-7115-4e08-94b9-aa61699d44d3)

- It should not show numbers 
- It should follow the guidelines defined by patternfly. Including turning red when there are error notifications.
- When the button is clicked a notification drawer opens (see other ticket)

This ticket also includes adding the data model to fetch the messages.

## Todo
- [x] DataLayer: Create Query + Manager + StateHelper + Store slice
- [x] DataLayer: Create Dummy Notification Badge component + Storybook entry with InstantApiHelper
- [x] Write test for Notification Badge (shows correct state based on response data)
- [x] Implement Notification Badge component

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3055?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
