### ISSUE TITLE
Add notification drawer

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3056]
Add a notification drawer that opens when you click the notification badge. The drawer shows all the notifications it receives through the API.

The top menu should contain the following actions:
- Mark all as read
- Clear all
- Show all notifications (goes to a page that contains a list of all notifications)

Each notification tile show the title + the severity + the message + the relative time. When a notification is clicked it should be marked as read. The the badge should change accordingly

The kebab menu of each message should contain:

- An action to mark it unread again
- An action to clear it from the list
- If a link is provided, a link to go to the correct page/report/...

The severity levels provided by the api should be mapped to those in the API as follows:
- message: default
- info: info
- success: success
- warning: warning
- error: danger

## Todo
- [x] Check Patternfly demo
- [x] Create component with empty actions
- [x] Create storybook entry
- [x] Create Command for clearing or reading a list of notifications
- [x] Create test for drawer actions
- [x] Add drawer to app
- [x] Create routeManager method for handling uri link
- [x] Create link for URI in ActionList

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3056?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
