### ISSUE TITLE
Create a notification center page

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#3067]
This page is accessible from the header in the notification drawer. For this type of content it is probably better to use [datalist ](https://www.patternfly.org/v4/components/data-list)and not data table.

- This page shows a table with all messages. The presentation should be similar to the drawer with the message body. It should show the severity (icon), title and date. When a message is not read, the title is shown in bold.
- The table is paged and sorted on the date.
- The page should offer filters for:
  - read
  - severity
  - text search on the title (partial match)
  - text search on the message (partial match)

Each row has a kebab menu with an action to mark the message read or unread.

## Todo
- [x] Write test for center page
- [x] Make data list component that looks like notification drawer
- [x] Write mock data
- [x] Write test for filters
- [x] Write test for paging
- [x] Add Query to page
- [x] Add DataList to page
- [x] Add paging to page
- [x] Add Filters to page

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/web-console/3067?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
