### ISSUE TITLE
[BUG]Service details callback page issues

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/web-console#4332]
# Task checklist
- [x] Solve the UUID being kept in the form
- [x] Change delete icon to 'Delete' text
- [x] Move collapsible arrow to the front of the row
- [x] Change the Minimal Log Level numerical code to text
- [x] Add a tooltip over the UUID to display full value instead of 4 first chars.
- [x] Truncate UUID after 8 char instead of 4 in table

# Issue 1

When you add a callback to your service details, and submit, the form isn't cleared correctly and the last used uuid remains in the id field. 

![image.png](https://images.zenhubusercontent.com/63107302b0093d27aee2da23/b40b79cc-c370-4dbe-97ad-751cb017e4a7)

# Issue 2
The icon from the delete button is not centered => According to PF guidelines, icons only is not a good practice. And because we are already using text in the add-button, we decided to change it to a text button too. 

# Issue 3
The arrow to expand the row needs to be moved in front of it, to be aligned with all other tables used so far. 

# Issue 4
After saving a callback, the Minimal Log Level is being displayed as a numerical code. We need to change that to the text label matching the code. This is already available in the API response.

# Issue 5
The UUID displayed in the ID collumn is being truncated, 4 characters is not enough. It would be better to show 8, add a tooltip with the full value.

**Comment by bartv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/frontend-600a82c1f666040010200918/issues/inmanta/web-console/4332?planning-poker) with Zenhub @LauraStordeur @matborowczyk
