### ISSUE TITLE
Can the concept of a qualifier inside a query be removed?

### ISSUE THREAD

**Issue by butterybread** [inmanta/web-console#458]
The query contains a qualifier property which unique defines the query.
Which in turn uniquely defines an entity.

We believe this concept is not really necessary.
If during refactor it appears to be necessary, we should add an explanation to the design docs.

# Todo

- [x] Investigate if the qualifier can be removed
- [x] if not document in the design what the qualifier is
- [x] if so remove it
