### ISSUE TITLE
Add compile report detail view

### ISSUE THREAD

**Issue by bartv** [inmanta/web-console#976]
This is a page that show the full compile report. Similar to what the current report page offers (but better of course).

The page has multiple sections:
1. A section that list all the high level details
2. An overview of the errors (see diagnose page)
3. A section that list all the stages/reports 

## Section 1: Details

This should list all the high level information about the compile run. The required information is:

- Requested, Started and Completed time in full dates. Computing the diff is very useful as well. A possible visualization for this is a timeline/graph with the three dates and on the edges that connect the dates the actual time. This can also be a row with 5 cols that show this, however it should be visually clear what the timestamps and the diffs are. The following example has the same "feel" 
![image](https://user-images.githubusercontent.com/10819/125849136-16bf28d0-6709-4c7e-8dec-43e0bab53bc8.png)
- Show the status of export (do_export), update (force_update) and success booleans. Success should be supported with a success/fail icon and color
- It should also list the message and if defined the trigger (defined as message and type in the metadata dict)
-  List the environment variables with their values stored in the environment variables dict

## Section 2: Errors

If the compiler_data objects contains a list of errors, these errors need to be shown/rendered in the errors section. If it is empty this section should not be shown. Reuse the diagnose view compile error component to show this.

## Section 3: Details

This section is a table/data list that show in the correct order each of the reports returned. There should be no sorting/paging/filtering so a datalist might work better here. Each record should be collapsible to show the out and err stream

The un view should show:
- name
- short version of the command (see screenshot in epic)
- the relative time to the started of the full run for this stage
- the duration of this stage (completed-started)
- When return code > 0 the line should be marked with red-50

When the row is opened it should show:
- the full command (monospace) and when double clicked it should be selected in full. copy action is desired.
- the actual return code
- the outstream. copy action and/or download action is desired.
- the errstream.  copy action and/or download action is desired.

See our mgmt orchestrator that these can be quite long and heavy to load: http://mgmt.ii.inmanta.com:8888/dashboard/#!/environment/f81be80b-8582-499f-b002-7cdd2f2df98a/compilereport

This data is log output so a monospace font has to be used. Having a "terminal" like box with a darker background might be useful as well.

## Tasks

- [ ] Page
- [ ] Data Fetching + Loading + Error + Success
- [x] Timeline Component (Storybook)
- [ ] Section Info (render json blob)
- [ ] Section Info (use Timeline Component)
- [ ] Section Errors
- [ ] Section Details
